name = str(input("โปรดกรอกชื่อจริง-นามสกุล : "))
age = int(input("โปรดกรอกอายุ : "))
id = int(input("โปรดกรอกรหัสนักศึกษา : "))
gl = int(input("โปรดกรอกระดับชั้น : "))
nick = str(input("โปรดกรอกชื่อเล่น : "))
hight = float(input("โปรดกรอกส่วนสูง : "))
weight = float(input("โปรดกรอกน้ำหนัก : "))
hplusw = hight + weight
print(f"ชื่อ:  "+{name},"อายุ:"+{age}+"ปี")
print(f"รหัสประจำตัวนักเรียน: "+{id}+"ระดับชั้น: "+gl)
print(f"ชื่อเล่น: "+{nick})
print(f"ส่วนสูง: "+{hight}+"เซนติเมตร"+"น้ำหนัก: "+{weight}+"น้ำหนัก")
print(f"ส่วนสูง + น้ำหนัก = "+{hplusw})